version: "3.9"

services:
  backend-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    depends_on:
      - mongodb
    ports:
      - "{{cookiecutter.port}}:{{cookiecutter.port}}"
    networks:
      - backend-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    env_file:
      - .env
    volumes:
      - mongodb-volume:/data/db
    networks:
      - backend-network

volumes:
  mongodb-volume:

networks:
  backend-network:
    name: backend-network
    driver: bridge