version: "3"

services:
  app:
    build: .
    restart: on-failure
    depends_on:
      - mongodb
    ports:
      - "{{cookiecutter.port}}:{{cookiecutter.port}}"

  mongodb:
    image: mongo
    restart: always
    env_file:
      - .env
