version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    depends_on:
      - mongodb
    ports:
      - "{{cookiecutter.port}}:{{cookiecutter.port}}"
    networks:
      - backend

  mongodb:
    image: mongo
    restart: always
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    name: {{cookiecutter.project_slug}}_network
    driver: bridge