version: "3.9"

services:
  app:
    build:
      context: "{{cookiecutter.project_slug}}"
      dockerfile: "docker/Dockerfile"
    restart: on-failure
    depends_on:
      - mongodb
    ports:
      - "8088:8088"

  mongodb:
    image: mongo
    restart: always
